### PR TITLE
Dickbutt69.

### PR DESCRIPTION
**Pull request by kid-icarus**

### CODE REVIEW

**Comment by operatorjen** [comment]
wat

**Comment by tec27** [comment]
Needs tests.

**Comment by operatorjen** [comment]
:warning:

**Comment by lauradegroot** [comment]
typical

**Comment by Maciek416** [comment]
this is an outrage

**Comment by kid-icarus** [comment]
dealwithit

**Comment by operatorjen** [comment]
it's like they dont think we're being serious here @btford - i don't even.

**Comment by btford** [comment]
kids these days

**Pull request closed without merging**
