### PR TITLE
cryptomail tin foil

### PR DESCRIPTION
**Pull request by cryptomail**

### CODE REVIEW

**Comment by cryptomail** [comment]
lemme know if that's acceptable or not

**Comment by btford** [comment]
Looks great :+1:

**Comment by btford** [comment]
Landed as bf191adca4b9b6bd152ff7664d780f2bca578f3e. I rotated and fixed the path of the img for ya. :)

**Comment by cryptomail** [comment]
oh rats...thanks!  I just copied hep's template haha!  wooty pebbles thanks for letting me into the ground floor!

**Comment by btford** [comment]
no worries <3

**Pull request closed without merging**
